// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHV-N7QHirJS7rm6J-99cVbRW7ouNf7zY',
    appId: '1:1087079661200:web:57c298dc868d9f699ee215',
    messagingSenderId: '1087079661200',
    projectId: 'organic-area-409503',
    authDomain: 'organic-area-409503.firebaseapp.com',
    storageBucket: 'organic-area-409503.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpF6IdWfQ5Q-vZXPfVx-9KrG9-JpD8Lgo',
    appId: '1:1087079661200:android:a4dcf2fb286e9ab19ee215',
    messagingSenderId: '1087079661200',
    projectId: 'organic-area-409503',
    storageBucket: 'organic-area-409503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC569bz08zfSWZZ4JEgwnvUuqnuOfWMmZk',
    appId: '1:1087079661200:ios:368888fa57206f979ee215',
    messagingSenderId: '1087079661200',
    projectId: 'organic-area-409503',
    storageBucket: 'organic-area-409503.appspot.com',
    iosBundleId: 'com.example.shoutOutTo2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC569bz08zfSWZZ4JEgwnvUuqnuOfWMmZk',
    appId: '1:1087079661200:ios:ed6d01a604b6c21f9ee215',
    messagingSenderId: '1087079661200',
    projectId: 'organic-area-409503',
    storageBucket: 'organic-area-409503.appspot.com',
    iosBundleId: 'com.example.shoutOutTo2024.RunnerTests',
  );
}
